### ISSUE TITLE
artist image  returns the same image

### ISSUE THREAD

**Issue by ByteCollector** [inflatablefriends/lastfm#148] opened 2019-05-04 14:23 UTC

**Comment by ByteCollector** [comment] 2019-05-04 14:28
It;s weird but I have been receiving the same kind of artist image. This is happening 2 days ago. Is it a bug on lastfm? Here's the pic that I've been receiving when i request of an artist image.
![lastfmImage](https://user-images.githubusercontent.com/29355978/57180526-ef0c2100-6ebb-11e9-84b2-bb2e1676af78.jpg)

**Comment by klinge** [comment] 2019-05-06 08:45
I can verify that I get the same image as you are. The lastfm Artist.GetInfo method returns what seems like proper image urls but when entering the image url in a browser you just get the image with a star on that you are seeing. 

I don't really have time to troubleshoot but my guess is that this isn't a bug in the code but rather that artist images are missing on the content delivery network that lastfm is using.. 

Example of returned values from Artist.GetInfo

```
{
    "artist": {
        "name": "Steely Dan",
        "mbid": "e01c3376-15fa-40d7-b747-5f219bdefdd7",
        "url": "https://www.last.fm/music/Steely+Dan",
        "image": [
            {
                "#text": "https://lastfm-img2.akamaized.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png",
                "size": "small"
            },
            {
                "#text": "https://lastfm-img2.akamaized.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png",
                "size": "medium"
            },
            {
                "#text": "https://lastfm-img2.akamaized.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png",
                "size": "large"
            },
            {
                "#text": "https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
                "size": "extralarge"
            },
            {
                "#text": "https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
                "size": "mega"
            },
            {
                "#text": "https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
                "size": ""
            }
        ],
        "streamable": "0",
```

**Comment by ByteCollector** [comment] 2019-05-06 15:58
Thank you for responding, I have already  found also having the same problem https://stackoverflow.com/tags/last.fm.  I have been using this api for almost 2 years now and I don’t have any problem.  All we have to do is wait, maybe they are updating.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rikkit** [comment] 2019-05-09 10:52
@ByteCollector weird! It doesn't seem to be caused by this project though, so I'm going to close this issue. Feel free to reopen if you discover otherwise! Cheers

**Closed by rikkit** 2019-05-09 10:52 UTC
Labels: api

**Comment by ByteCollector** [comment] 2019-05-09 18:24
Thanks for responding!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
